services:
  - type: web
    name: toolkit
    runtime: node
    plan: free
    buildCommand: npx prisma generate && npm run build
    startCommand: node .next/standalone/server.js
    envVars:
      - key: NODE_ENV
        value: production

databases:
  - name: toolkit-db
    databaseName: toolkit
    plan: free
    region: oregon